package com.guedim.pgbulkinsert.pgbulkinsert.model;

public enum PaymentReferenceExtraParameterName {

  AUTHORIZATION_STATUS("AUTHORIZATION_STATUS"),
  AUTHORIZATION_VALUE("AUTHORIZATION_VALUE"),
  BARCODE_PM_BAPRO("BARCODE_PM_BAPRO"),
  BARCODE_PM_COBRO_EXPRESS("BARCODE_PM_COBRO_EXPRESS"),
  BARCODE_PM_PAGOFACIL("BARCODE_PM_PAGOFACIL"),
  BARCODE_PM_RAPIPAGO("BARCODE_PM_RAPIPAGO"),
  BARCODE_PM_RIPSA("BARCODE_PM_RIPSA"),
  PAYMENT_REFERENCE_BATCH("PAYMENT_REFERENCE_BATCH"),
  PAYMENT_REFERENCE_CC("PAYMENT_REFERENCE_CC"),
  PAYMENT_REFERENCE_DESIGN("PAYMENT_REFERENCE_DESIGN"),
  PAYMENT_REFERENCE_EMAIL_MESSAGE("PAYMENT_REFERENCE_EMAIL_MESSAGE"),
  PAYMENT_REFERENCE_EMAIL_SUBJECT("PAYMENT_REFERENCE_EMAIL_SUBJECT"),
  PAYMENT_REFERENCE_MERCHANT_ADDRESS("PAYMENT_REFERENCE_MERCHANT_ADDRESS"),
  PAYMENT_REFERENCE_MERCHANT_NAME("PAYMENT_REFERENCE_MERCHANT_NAME"),
  PAYMENT_REFERENCE_MERCHANT_PHONE("PAYMENT_REFERENCE_MERCHANT_PHONE"),
  PAYMENT_REFERENCE_REPLY_TO("PAYMENT_REFERENCE_REPLY_TO"),
  PAYMENT_REFERENCE_TO("PAYMENT_REFERENCE_TO"),
  REFERENCE_PM_BALOTO("REFERENCE_PM_BALOTO"),
  REFERENCE_PM_EFECTY("REFERENCE_PM_EFECTY"),
  REFERENCE_PM_BAD_EFECTY("REFERENCE_PM->EFECTY"),
  SERVICE_CODE_PM_BALOTO("SERVICE_CODE_PM_BALOTO"),
  SERVICE_CODE_PM_EFECTY("SERVICE_CODE_PM_EFECTY"),
  SERVICE_CODE_PM_BAD_EFECTY("SERVICE_CODE_PM->EFECTY");
  
  private final String name;

  public String getName() {
    return name;
  }

  PaymentReferenceExtraParameterName(String name) {
    this.name = name;
  }

  
  
  
}
